### ISSUE TITLE
Add a .gitignore

### ISSUE THREAD

**Issue by AG6GR** [Tino-FRC-2473/FRC2018-Offseason#4]
A .gitignore file is a magic text file that goes in the main directory of a git repository and tells git what files it doesn't need to track. In particular, local settings, build outputs (class/jar files), and autogenerated files (.DS_Store).

For more info, take a look at https://help.github.com/articles/ignoring-files/ and https://github.com/Open-RIO/.gitignore

Remember: don't add any line of code that you don't understand! Ask me if you have any questions :)

**Comment by mvoodarla** [comment]
Resolved in https://github.com/Tino-FRC-2473/FRC2018-Offseason/issues/5.
